### ISSUE TITLE
Decorators not supported in React

### ISSUE THREAD

**Issue by jimmysafe** [Jeremboo/animated-mesh-lines#4]
I do really love the animated-mesh-lines library and I would like to implement it in my React project. I am using CRA and i adapt the code to my class based component.. however I get this syntax error in the console when trying to run the code:

`SyntaxError:Support for the experimental syntax 'decorators-legacy' isn't currently enabled (31:1):
  29 |  * * *******************
  30 |  */
> 31 | @FullScreenInBackground
     | ^
  32 | @HandleCameraOrbit({ x: 1, y: 1 }, 0.1)
  33 | class CustomEngine extends Engine {}
  34 | const engine = new CustomEngine();`

It looks like the decorators are not supported for react.

Is there a way to make this work in react, maybe not using decorators?

Thanks,

**Comment by jimmysafe** [comment]
I made it work! finally! for who is wondering how to enable the js decorators in CRA follow this tutorial:

https://medium.com/@michielsikma/adding-decorator-support-to-create-react-app-projects-using-react-app-rewired-df48e7ffd636

**Comment by Jeremboo** [comment]
Cool! I'm happy that you find a solution for yourself! I'll close the issue
